### ISSUE TITLE
Don't have a links, but I really want 

### ISSUE THREAD

**Issue by LencoDigitexer** [NathanFallet/CodeCommunity-Projects#2]
All my project is open source not have links in google play and play store. This for desktop and links for downloads in github releases . This projects is fun for me and my friends. But this new experience with github community - new and first flashmob. What links should I write?

**Comment by NathanFallet** [comment]
Links are links to all your platforms. If it is a mobile app then yes google play and app store is recommended. But if it is a website, put the website link, if it is an open source project, put the github repository, ... so any link that refers to your projects, there are no restrictions.
